Fixes #29: Don't show maven transfer progress by default
par-tec/super-sast pull request #44
Opened 2023-03-15 15:11 UTC by nocturn9x

# This PR
- Fixes #29 

# Note
- A specialized `--log-maven-progress` option has been added to instruct super-sast to dump the maven transfer progress to the log file

2023-03-15 15:11 UTC, nocturn9x commented
@ioggstream

2023-03-15 21:50 UTC, ioggstream requested changes
I won't add tool-specific variables. Instead the #29 issue suggests using a maven-specific env var: do you find any issue with the general idea detailed in #29? Please detail any shotcomings there.

2023-03-15 21:50 UTC, ioggstream commented on entrypoint.py
> +    parser.add_argument(
this solution is ok for a maven specific script.
In this case, adding a parameter for each specific tool (maven, trivy, ...) will make the tool unmaintainable in time.

2023-03-15 21:50 UTC, ioggstream commented on entrypoint.py
> +    tool, command, env, config_dir, log_file=stdout, run_all=True, maven_logs=False
passing tool-specific variables in this function leads to an unmaintainable script with tens of tool-specific variables.

This solution would be ok for a maven-specific tool

2023-03-15 21:52 UTC, nocturn9x commented
That looks like a misunderstanding on my part on the term "parameter". I'll work on the env var solution ASAP.

P.S. My bad!

2023-03-16 01:18 UTC, ioggstream commented
> my bad ;)

no problem at all. Feel free to ask if the proposed solution seems weird or if you think that the code review is missing some important point.

2023-03-18 14:15 UTC, nocturn9x commented
@ioggstream This should do it :)

2023-03-18 15:06 UTC, merged