#32 Added .semgrepignore
par-tec/super-sast pull request #55
Opened 2023-10-04 14:11 UTC by DrPlumcake

Semgrep now skips the files mentioned in the .semgrep file

`
┌─────────────┐
│ Scan Status │
└─────────────┘
  Scanning 43 files tracked by git with 1094 Code rules:

  Language      Rules   Files          Origin      Rules
 ─────────────────────────────        ───────────────────
  <multilang>      57      74          Community    1094
  yaml             28      14
  bash              4       2
  python          237       1
  dockerfile        5       1
  json              4       1

┌──────────────┐
│ Scan Summary │
└──────────────┘
Some files were skipped or only partially analyzed.
  Scan was limited to files tracked by git.
  **Scan skipped: 6 files matching .semgrepignore patterns**
  For a full list of skipped files, run semgrep with the --verbose flag.

Ran 1094 rules on 37 files: 7 findings.`

2023-10-05 07:39 UTC, ioggstream commented
1. place the file under config/ 
2. you can use it setting `SEMGREP_CONFIG_FILE=/app/config/.semgrepignore`
3. check whether the latest version of semgrep is capable to find the file in the home directory (e.g., /code).

2023-10-15 16:04 UTC, ioggstream requested changes

2023-10-15 16:04 UTC, ioggstream commented on tests/test_entrypoint.py
> +def create_semgrep_log(files_list):
Movw this code to test_semgrwp.py

2023-10-15 16:04 UTC, ioggstream commented on tox.ini
> +  python -m tests.test_semgrep setUp
This is clever, but you don't need it.

Add a pytest fixture in test_semgrep and it will run it for you.

2023-10-15 16:04 UTC, ioggstream commented on tests/test_semgrep.py
> +if __name__ == "__main__":
You don't need this. Pytest will run all tests for you

2023-10-15 16:04 UTC, ioggstream commented on tests/test_entrypoint.py
> +    if tool == "semgrep":
Create a single test without "if" in test_semgrep.py

2023-10-17 07:37 UTC, ioggstream commented
@DrPlumcake This PR is quite good, but we should not call `os.chdir`. Can you find a solution? :)

2023-10-17 11:11 UTC, DrPlumcake commented
I used monkeypatch, a fixture that overrides systemcalls (and other functions) inside the test environment, so it doesn't disturb other tests, then:

> _"All modifications will be undone after the requesting test function or fixture has finished."_

So it's better to use os.chdir() directly

2023-10-18 13:52 UTC, merged